# Generated by Django 4.2.2 on 2023-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Jucarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=128)),
                ('varsta', models.IntegerField()),
                ('brand', models.CharField(max_length=128)),
                ('categorii', models.ManyToManyField(to='api.categorie')),
            ],
        ),
    ]
