# Generated by Django 4.2.2 on 2023-07-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brand_remove_jucarie_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='jucarie',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brand'),
        ),
    ]
